### ISSUE TITLE
ea.DateiManager.stringArrayEinlesen(String[]) funktioniert nicht mit JDK9 oder höher

### ISSUE THREAD

**Issue by Lichtschalter-5000** [engine-alpha/engine-alpha#12]
**Was funktioniert nicht?**
Beim Versuch, ein "Programm" zu starten, dass die Methode stringArrayEinlesen(String[]) der Klasse DateiManager benutzt, erhalte ich foldende Exception:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at ea.DateiManager.stringArraySchreiben(DateiManager.java:126)
	at EineKlasse.<init>(EineKlasse.java:11)
	at EineKlasse.main(EineKlasse.java:30)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more

**Was benutze ich?**
IDE: IntelliJ IDEA 2018.1.5
EA: v3.2.0
Project SDK: JDK_1.8.0 (Die von IntelliJ IDEA automatisch heruntergeladene, glaube ich)
Module SDK: java version 9.0.4 (auch getestet mit 10.0.1)

**Beispielcode**

import ea.DateiManager;
import ea.Game;
public class EineKlasse extends Game {

    public EineKlasse() {
        super();

        String[] strings = {"a", "b", "c"};

        DateiManager.stringArraySchreiben(strings, "array.eaa");

        this.leseBuchstaben();

    }

    private void leseBuchstaben() {
        String[] lieblingsBuchstaben = DateiManager.stringArrayEinlesen("array.eaa");
        for (int i = 0; i < lieblingsBuchstaben.length; i++) {
            System.out.println(lieblingsBuchstaben[i]);
        }
    }

    @Override
    public void tasteReagieren(int i) {

    }

    public static void main(String[] args) {
        new EineKlasse();
    }

}

Lösung: JDK8 verwenden. 
[Hier](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) habe ich mehr Information darüber gefunden.

Kann auf der engine-Seite etwas dagegen gemacht werden? Oder ist das nur eine Sache von Abhängigkeiten, die man selbst einstellen muss?

**Comment by Lichtschalter-5000** [comment]
Siehe Pull Request #13 ...
